version: 2.0
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: dorpolo
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build main image
          command: |
            HEROKU_DST=registry.heroku.com/world-cup-22/web

            curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

            docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
            docker build -f Dockerfile \
              -t $HEROKU_DST .

            echo "image built successfully"
            docker push $HEROKU_DST
            echo docker pushed successfully into $HEROKU_DST
      - run:
          name: Build and push Docker image to Heroku
          command: |
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a world-cup-2 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a world-cup-2 web


            heroku login -i
            heroku container:release -a world-cup-22 web




workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: world-cup-2022

