version: 2.0
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: dorpolo
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build main image
          command: |
            HEROKU_DST=registry.heroku.com/world-cup-22/web
            sudo curl https://cli-assets.heroku.com/install.sh | sh

            docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
            docker build -f Dockerfile
            echo "image built successfully"

            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a world-cup-22 web
            HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a world-cup-22 web

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: world-cup-2022

