version: 2.0
jobs:
  check-authentication:
    description: |
      Verifies the Heroku API key has been added so we can authenticate.
    parameters:
      print-whoami:
        default: false
        description: Print the result of heroku auth:whoami.
        type: boolean
    steps:
      - run:
          name: Verify HEROKU_TOKEN is set
          command: |
            if [[ $HEROKU_TOKEN == "" ]]; then
              echo "No Heroku API key set, please set the HEROKU_API_KEY environment variable."
              echo "This can be found by running the `heroku auth:token` command locally."
              exit 1
            else
              echo "Heroku API key found."
            <<#parameters.print-whoami>>
              heroku auth:whoami
            <</parameters.print-whoami>>
            fi

  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: dorpolo
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Image build
          command: |
            HEROKU_APP_NAME=world-cup-22
            HEROKU_DST=registry.heroku.com/${HEROKU_APP_NAME}/web

            docker build -f Dockerfile \
              -t $HEROKU_DST . \
              --build-arg PG_PASS=$PG_PASS
            echo "image built successfully"
      - run:
          name: Install Heroku CLI (If not installed)
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=dorpolo --password=$HEROKU_TOKEN registry.heroku.com
      - run:
          name: Deploy Heroku Docker Container
          command: |
            heroku container:push web -a world-cup-22
            heroku container:release -a world-cup-22 web

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: world-cup-2022
