version: 2.0
jobs:
  build:
    docker:
      - image: alpine
        auth:
          username: dorpolo
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build main image
          command: |
            docker build -t polo .
            echo "image built successfully"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: world-cup-2022

