version: 2.0
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: dorpolo
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Image build
          command: |
            HEROKU_APP_NAME=world-cup-22
            HEROKU_DST=registry.heroku.com/${HEROKU_APP_NAME}/web

            echo ${PG_PASS}

            docker build -f Dockerfile \
              -t $HEROKU_DST . \
              --build-arg POSTGRES_PASS=${PG_PASS}
            echo "image built successfully"
      - run:
          name: Install Heroku CLI (If not installed)
          command: |
            if [[ $(command -v heroku) == "" ]]; then
              curl https://cli-assets.heroku.com/install.sh | sh
            else
              echo "Heroku is already installed. No operation was performed."
            fi
      - run:
          name: netrc config
          command: |
            chmod +x setup-heroku.sh
            sh setup-heroku.sh $HEROKU_TOKEN
#      - run:
#          name: Login into Heroku Docker Repository
#          command: |
#            docker login --username=dorpolo --password=$HEROKU_TOKEN registry.heroku.com
      - run:
          name: Deploy Heroku Docker Container
          command: |
            heroku container:login
            heroku container:push web -a world-cup-22
            heroku container:release -a world-cup-22 web

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: world-cup-2022
