version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build:
    docker:
      - image: cimg/go:1.17
        auth:
          username: dorpolo
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build main image
          command: |
            echo "working in Progress ..."
            echo $(pwd)
            echo $(ls)
#            docker build -t polo .
#            echo "image built successfully"

workflows:
  sample:
    jobs:
      - build:
          context: world-cup-2022

