dz_array = {
    "public":{
        "favicon":"images/favicon.png",
        "title":"Zenix - Crypto Admin Dashboard Django Template"
    },
    "global":{
        "css":[
                "vendor/bootstrap-select/dist/css/bootstrap-select.min.css",
                "css/style.css"
            ],

        "js":[
                "vendor/global/global.min.js",
                "vendor/bootstrap-select/dist/js/bootstrap-select.min.js",
                "js/custom.js",
                "js/deznav-init.js",
                "js/demo.js",
                "js/styleSwitcher.js"
            ]

    },
    "pagelevel":{
        "css": {
            "index":[
                'vendor/chartist/css/chartist.min.css',
                'vendor/owl-carousel/owl.carousel.css'
            ],
            "index_2":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/owl-carousel/owl.carousel.css"
            ],
            "my_wallets":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/swiper/css/swiper-bundle.min.css",
                "vendor/owl-carousel/owl.carousel.css"
            ],
            "tranasactions":[
                "vendor/datatables/css/jquery.dataTables.min.css"
            ],
            "coin_details":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/bootstrap-daterangepicker/daterangepicker.css"
            ],
            "portofolio":[
                "vendor/chartist/css/chartist.min.css"
            ],
            "market_capital":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/datatables/css/jquery.dataTables.min.css"
            ],
            #App
            #App Profile
            "app_profile":[
                "vendor/lightgallery/css/lightgallery.min.css",
                "vendor/magnific-popup/magnific-popup.css"
            ],
            #Post Details
            "post_details":[
                "vendor/lightgallery/css/lightgallery.min.css",
                "vendor/magnific-popup/magnific-popup.css"
            ],
            #Chat
            "page_chat":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/owl-carousel/owl.carousel.css"
            ],
            #Project
            "project_list":[
                "vendor/chartist/css/chartist.min.css"
            ],
            "project_card":[
                "vendor/chartist/css/chartist.min.css"
            ],
            #User
            "user_list_datatable":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/datatables/css/jquery.dataTables.min.css"
            ],
            "user_list_column":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/datatables/css/jquery.dataTables.min.css"

            ],
            #Contact
            "contact_list":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/datatables/css/jquery.dataTables.min.css"
            ],

            "contact_card":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/owl-carousel/owl.carousel.css"

            ],
            #Email
            "email_compose":[
                "vendor/dropzone/dist/dropzone.css"
            ],
            "email_inbox":[],
            "email_read":[],
            #Calender
            "app_calender":[
                "vendor/fullcalendar/css/main.min.css"
            ],
            #Shop
            "ecom_product_grid":[],
            "ecom_product_list":[
                "vendor/star-rating/star-rating-svg.css"
            ],
            "ecom_product_detail":[
                "vendor/star-rating/star-rating-svg.css",
                "vendor/owl-carousel/owl.carousel.css"
            ],
            "ecom_product_order":[],
            "ecom_checkout":[],
            "ecom_invoice":[],
            "ecom-customers":[],
            #Chart
            "chart-flot":[],
            "chart_morris":[],
            "chart_chartjs":[],
            "chart_chartist":[
                "vendor/chartist/css/chartist.min.css"
            ],
            "chart_sparkline":[],
            "chart_peity":[],
            #pugins
            "uc_select2":[
                "vendor/select2/css/select2.min.css",

            ],
            "uc_nestable":[
                "vendor/nestable2/css/jquery.nestable.min.css"
            ],
            "uc_noui_slider":[
                "vendor/nouislider/nouislider.min.css"
            ],
            "uc_sweetalert":[
                "vendor/sweetalert2/dist/sweetalert2.min.css"
            ],
            "uc_toastr":[
                "vendor/toastr/css/toastr.min.css"
            ],
            "map_jqvmap":[
                "vendor/jqvmap/css/jqvmap.min.css"
            ],
            "uc_lightgallery":[
                "vendor/lightgallery/css/lightgallery.min.css"
            ],
            "widget-basic":[
                "vendor/chartist/css/chartist.min.css"
            ],
            #forms
            "form_element":[],
            "form_wizard":[
                "vendor/jquery-smartwizard/dist/css/smart_wizard.min.css"
            ],
            "form_editor_summernote":[],
            "form_pickers":[
                "vendor/bootstrap-daterangepicker/daterangepicker.css",
                "vendor/clockpicker/css/bootstrap-clockpicker.min.css",
                "vendor/jquery-asColorPicker/css/asColorPicker.min.css",
                "vendor/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css",
                "vendor/pickadate/themes/default.css",
                "vendor/pickadate/themes/default.date.css",
            ],
            "form_validation_jquery":[],
            #table
            "table_datatable_basic":[
                "vendor/datatables/css/jquery.dataTables.min.css"
            ],
             #pages
            "page_register":[],
            "page_login":[],
            "page_error_400":[],
            "page_error_403":[],
            "page_error_404":[],
            "page_error_500":[],
            "page_error_503":[],
            "page_lock_screen":[],
            "page_empty":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/owl-carousel/owl.carousel.css",
            ],
            "page_lock_screen":[],

            "test":[
                "vendor/chartist/css/chartist.min.css",
                "vendor/datatables/css/jquery.dataTables.min.css"
            ]

            },
##********************************************************

# Javascript

#**********************************************************
        "js":{
            "index":[
                'vendor/chart.js/Chart.bundle.min.js',
                'vendor/peity/jquery.peity.min.js',
                'vendor/apexchart/apexchart.js',
                'js/dashboard/dashboard-1.js',
                'vendor/owl-carousel/owl.carousel.js',
            ],
            "index_2":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/peity/jquery.peity.min.js",
                "vendor/apexchart/apexchart.js",
                "js/dashboard/dashboard-1.js",
                "vendor/owl-carousel/owl.carousel.js"
            ],
            "my_wallets":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/peity/jquery.peity.min.js",
                "vendor/apexchart/apexchart.js",
                "js/dashboard/my-wallet.js",
                "vendor/owl-carousel/owl.carousel.js",
                "vendor/swiper/js/swiper-bundle.min.js"
            ],
            "tranasactions":[
                "vendor/datatables/js/jquery.dataTables.min.js",
                "js/plugins-init/datatables.init.js",

            ],
            "coin_details":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/apexchart/apexchart.js",
                "js/dashboard/coin-details.js",
                "vendor/moment/moment.min.js",
                "vendor/bootstrap-daterangepicker/daterangepicker.js"

            ],
            "portofolio":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/apexchart/apexchart.js",
                "js/dashboard/portofolio.js"

            ],
            "market_capital":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/peity/jquery.peity.min.js",
                "vendor/apexchart/apexchart.js",
                "vendor/datatables/js/jquery.dataTables.min.js",
                "js/plugins-init/datatables.init.js",
                "js/dashboard/market-capital.js"

            ],
            #App
            #App Profile
            "app_profile":[
                "vendor/lightgallery/js/lightgallery-all.min.js",
                "vendor/magnific-popup/jquery.magnific-popup.js"
            ],
            #Post Details
            "post_details":[
                "vendor/lightgallery/js/lightgallery-all.min.js",
                "vendor/magnific-popup/jquery.magnific-popup.js"

            ],
            #Chat
            "page_chat":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/peity/jquery.peity.min.js",
                "vendor/apexchart/apexchart.js",
                "js/dashboard/chat.js",
                "vendor/owl-carousel/owl.carousel.js"
            ],
            #Project
            "project_list":[
                "vendor/chart.js/Chart.bundle.min.js"
            ],
            "project_card":[
                "vendor/chart.js/Chart.bundle.min.js"

            ],
            #User
            "user_list_datatable":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/datatables/js/jquery.dataTables.min.js",
                "js/plugins-init/datatables.init.js"
            ],
            "user_list_column":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/datatables/js/jquery.dataTables.min.js",
                "js/plugins-init/datatables.init.js"
            ],
            #Contact
            "contact_list":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/datatables/js/jquery.dataTables.min.js",
                "js/plugins-init/datatables.init.js"
            ],
            "contact_card":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/peity/jquery.peity.min.js",
                "vendor/apexchart/apexchart.js",
                "js/dashboard/contact.js",
                "vendor/owl-carousel/owl.carousel.js"
            ],
            #Email
            "email_compose":[
                "vendor/dropzone/dist/dropzone.js"
            ],
            "email_inbox":[

            ],
            "email_read":[],
            #Calender
            "app_calender":[
                "vendor/moment/moment.min.js",
                "vendor/fullcalendar/js/main.min.js",
                "js/plugins-init/fullcalendar-init.js"
            ],
            #Shop
            "ecom_product_grid":[],
            "ecom_product_list":[
                "vendor/star-rating/jquery.star-rating-svg.js"
            ],
            "ecom_product_detail":[
                "vendor/star-rating/jquery.star-rating-svg.js",
                "vendor/owl-carousel/owl.carousel.js"
            ],
            "ecom_product_order":[],
            "ecom_checkout":[],
            "ecom_invoice":[],
            "ecom-customers":[
                "vendor/highlightjs/highlight.pack.min.js"
            ],
            #Chart
            "chart_flot":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/flot/jquery.flot.js",
                "vendor/flot/jquery.flot.pie.js",
                "vendor/flot/jquery.flot.resize.js",
                "vendor/flot-spline/jquery.flot.spline.min.js",
                "js/plugins-init/flot-init.js"
            ],
            "chart_morris":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/raphael/raphael.min.js",
                "vendor/morris/morris.min.js",
                "js/plugins-init/morris-init.js",
            ],
            "chart_chartjs":[
                "vendor/chart.js/Chart.bundle.min.js",
                "js/plugins-init/chartjs-init.js"

            ],
            "chart_chartist":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/chartist/js/chartist.min.js",
                "vendor/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js",
                "js/plugins-init/chartist-init.js"
            ],
            "chart_sparkline":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/jquery-sparkline/jquery.sparkline.min.js",
                "js/plugins-init/sparkline-init.js",
                "vendor/svganimation/vivus.min.js",
                "vendor/svganimation/svg.animation.js",

            ],
            "chart_peity":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/peity/jquery.peity.min.js",
                "js/plugins-init/piety-init.js",

            ],
            #plugins
            "uc_select2":[
                "vendor/select2/js/select2.full.min.js",
                "js/plugins-init/select2-init.js"
            ],
            "uc_nestable":[
                "vendor/nestable2/js/jquery.nestable.min.js",
                "js/plugins-init/nestable-init.js"

            ],
            "uc_noui_slider":[
                "vendor/nouislider/nouislider.min.js",
                "vendor/wnumb/wNumb.js",
                "js/plugins-init/nouislider-init.js"
            ],
            "uc_sweetalert":[
                "vendor/sweetalert2/dist/sweetalert2.min.js",
                "js/plugins-init/sweetalert.init.js",

            ],
            "uc_toastr":[
                "vendor/toastr/js/toastr.min.js",
                "js/plugins-init/toastr-init.js"
            ],
            "map_jqvmap":[
                "vendor/jqvmap/js/jquery.vmap.min.js",
                "vendor/jqvmap/js/jquery.vmap.world.js",
                "vendor/jqvmap/js/jquery.vmap.usa.js",
                "js/plugins-init/jqvmap-init.js"

            ],
            "uc_lightgallery":[
                "vendor/lightgallery/js/lightgallery-all.min.js"

            ],
            "widget-basic":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/apexchart/apexchart.js",
                "vendor/chartist/js/chartist.min.js",
                "vendor/chartist-plugin-tooltips/js/chartist-plugin-tooltip.min.js",
                "vendor/flot/jquery.flot.js",
                "vendor/flot/jquery.flot.pie.js",
                "vendor/flot/jquery.flot.resize.js",
                "vendor/flot-spline/jquery.flot.spline.min.js",
                "vendor/jquery-sparkline/jquery.sparkline.min.js",
                "js/plugins-init/sparkline-init.j",
                "vendor/peity/jquery.peity.min.js",
                "js/plugins-init/piety-init.js",
                "js/plugins-init/widgets-script-init.js",
            ],
            "form_element":[
                "vendor/ckeditor/ckeditor.js"
            ],
            "form_wizard":[
                "vendor/jquery-steps/build/jquery.steps.min.js",
                "vendor/jquery-validation/jquery.validate.min.js",
                "js/plugins-init/jquery.validate-init.js",
                "vendor/jquery-smartwizard/dist/js/jquery.smartWizard.js",

            ],
            "form_editor_summernote":[
                "vendor/ckeditor/ckeditor.js"
            ],
            "form_pickers":[
                "vendor/moment/moment.min.js",
                "vendor/bootstrap-daterangepicker/daterangepicker.js",
                "vendor/clockpicker/js/bootstrap-clockpicker.min.js",
                "vendor/jquery-asColor/jquery-asColor.min.js",
                "vendor/jquery-asGradient/jquery-asGradient.min.js",
                "vendor/jquery-asColorPicker/js/jquery-asColorPicker.min.js",
                "vendor/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js",
                "vendor/pickadate/picker.js",
                "vendor/pickadate/picker.time.js",
                "vendor/pickadate/picker.date.js",
                "js/plugins-init/bs-daterange-picker-init.js",
                "js/plugins-init/clock-picker-init.js",
                "js/plugins-init/jquery-asColorPicker.init.js",
                "js/plugins-init/material-date-picker-init.js",
                "js/plugins-init/pickadate-init.js",
            ],
            "form_validation_jquery":[
                "vendor/jquery-validation/jquery.validate.min.js",
                "js/plugins-init/jquery.validate-init.js"
            ],
            #table
            "table_datatable_basic":[
                "vendor/datatables/js/jquery.dataTables.min.js",
                "js/plugins-init/datatables.init.js",
                "",
            ],
             #pages
            "page_register":[],
            "page_login":[],
            "page_error_400":[],
            "page_error_403":[],
            "page_error_404":[],
            "page_error_500":[],
            "page_error_503":[],
            "page_lock_screen":[],
            "page_empty":[
                "vendor/chart.js/Chart.bundle.min.js",
                "vendor/peity/jquery.peity.min.js",
                "vendor/apexchart/apexchart.js",
                "js/dashboard/dashboard-1.js",
                "vendor/owl-carousel/owl.carousel.js",

            ],
            "page_lock_screen":[],

            "test":[
                "vendor/datatables/js/jquery.dataTables.min.js",
                "js/plugins-init/datatables.init.js",
                "js/dashboard/market-capital.js"
            ]
            }

        }

}
