# Generated by Django 3.2.9 on 2022-06-30 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='League Name')),
                ('logo', models.CharField(max_length=20, unique=True, verbose_name='Logo')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('use_default_policy', models.BooleanField(default=True)),
                ('policy_gs_90_min_score', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5)], default=3)),
                ('policy_gs_90_min_winner', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('policy_no_90_min_score', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5)], default=3)),
                ('policy_no_120_min_winner', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1)),
                ('policy_top_scorer', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2)),
                ('policy_top_assist', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2)),
                ('policy_best_team', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
